name: Bug Report
description: Report unexpected behavior, a crash, or other issues
labels: ["bug"]
assignees:
  - raiguard
body:
  - type: markdown
    attributes:
      value: "
        Please make sure to [search issues](https://github.com/raiguard/kakoune/issues?q=is%3Aissue) before creating a new one, to avoid duplicates and centralize conversations. If you wish to ask a question or provide general feedback, please use the [discussions](https://github.com/raiguard/krastorio-2/discussions) tab.

        Please replicate the issue on the **latest version** of the mod. Check the mod portal for updates before filing your issue.

        For localization issues, refer to the [Krastorio 2 Crowdin page](https://crowdin.com/project/krastorio-2). That is where all localization is performed.

        ## Save file and log

        You must attach the save file where the issue occured, and upload `factorio-current.log`, in order for your issue to be accepted. Failure to do so will result in your issue being closed as invalid.

        Attach these files by dragging them into the `Description` field below."
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: A brief explanation of the issue. Please include screenshots if applicable. Please attach your save file by dragging it into this textfield.
      placeholder: I cannot craft iron plates by hand.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Exact steps to replicate the issue.
      placeholder: |
        1. Open the attached save file
        2. Go to '...'
        3. Click on '...'
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Factorio version"
      description: "The version of Factorio that you are running."
    validations:
      required: true
  - type: input
    id: username
    attributes:
      label: "In-game username"
      description: "Your in-game username is required in some cases for exact reproduction."
    validations:
      required: true


