name: Sync with Crowdin

on:
  schedule:
    - cron: '0 16 * * SUN'
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync with Crowdin
      uses: crowdin/github-action@1.1.0
      with:
        upload_sources: true
        upload_translations: false
        download_translations: true
        config: '.crowdin.yml'
        pull_request_title: 'Update Crowdin translations'
        commit_message: 'Update Crowdin translations'
        export_only_approved: false
        skip_untranslated_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
